spring.h2.console.enabled=true
spring.datasource.name=runnerz
spring.datasource.generate-unique-name=false

logging.level.org.springframework.jdbc=INFO

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
management.info.env.enabled=true

info.app.name=Runners App
info.app.description=Run tracking REST API
info.app.version=0.0.1
